spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop # Change to "create-drop" to recreate tables on every application start
    show-sql: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  jwt-secret: ${JWT_API_KEY}
  prediction-url: ${PYTHON_API_URL}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG