spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  datasource:
    url:
    driverClassName: org.h2.Driver
    username:
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop # Change to "create-drop" to recreate tables on every application start
    show-sql: true

cloudinary:
  cloud-name:
  api-key:
  api-secret:

app:
  jwt-secret:
  prediction-url:

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG